site_name: Dynamic Consistency Boundary
site_description: DCB â€“ A simpler and more flexible approach to consistency in event-driven systems
site_url: https://dcb.events
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: deep orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: deep orange

nav:
  - DCB: index.md
  - Specification: specification.md
  - Examples:
      - examples/index.md
      - Course subscriptions: examples/course-subscriptions.md
      - Unique username: examples/unique-username.md
      - Dynamic product price: examples/dynamic-product-price.md
      #- Opt-In Token (tbd): examples/opt-in-token.md
      #- Invoice number (tbd): examples/invoice-number.md
      #- Prevent record duplication (tbd): examples/prevent-record-duplication.md
  - Related topics:
      - topics/index.md
      - Aggregates: topics/aggregates.md
      - Event-Sourced Aggregate: topics/event-sourced-aggregate.md
      - Projections: topics/projections.md
      #- DCB vs Outbox Pattern (tbd): topics/dcb-vs-outbox-pattern.md
      #- DCB with a traditional Event Store (tbd): topics/dcb-with-a-traditional-event-store.md
      #- DCB without Event Sourcing (tbd): topics/dcb-without-event-sourcing.md
      #- Performance (tbd): topics/performance.md
  - Resources:
      - resources/index.md
      - Libraries: resources/libraries.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - About: about.md

markdown_extensions:
  - extensions.replace_dcb_scenarios
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - pymdownx.blocks.caption
extra:
  #generator: false
  social:
    - icon: simple/github
      link: https://github.com/dcb-events/dcb-events.github.io

plugins:
  - search
  - glightbox

hooks:
  - hooks/copyright.py

watch:
  - includes

extra_javascript:
  - https://unpkg.com/@antonz/codapi@0.19.10/dist/snippet.js
  - assets/js/dcb-scenario.bundle.js
extra_css:
  - https://unpkg.com/@antonz/codapi@0.19.10/dist/snippet.css
  - assets/css/custom.css
